import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";
import Footer from "./Components/Footer";



const interFont = Inter({ subsets: ["latin"], variable: "--font-inter" });
const poppinsFont = Poppins({ subsets: ["latin"], weight: ["700"], variable: "--font-poppins" });

export const metadata: Metadata = {
  title: "TrioNex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${interFont.variable} ${poppinsFont.variable}`}>
      <body className={interFont.className}>
          <Header />
          {children}
          <Footer />
      </body>
    </html>
  );
}
